### ISSUE TITLE
AADSTS700213: No matching federated identity record found 

### ISSUE THREAD

**Issue by micahel71** [microsoft/terraform-provider-fabric#23]
### 🐛 What happened?

Running in Azure Devops with an OIDC configured Service Connection, the call for a "data.fabric_capacity.capacity" fails with this message:
```
Terraform has been successfully initialized!
+ terraform plan -out=fabric_plan.tfplan -var-file=/home/vsts/work/1/self/config/lab/terraform.tfvars
data.fabric_capacity.capacity: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: invalid_client
│ 
│   with data.fabric_capacity.capacity,
│   on workspace.tf line 1, in data "fabric_capacity" "capacity":
│    1: data "fabric_capacity" "capacity" {
│ 
│ AADSTS700213: No matching federated identity record found for presented
│ assertion subject 'p://<ADO_ORG>/<ADO_PROJECT>/<ADO_NAME_OF_PIPELINE>'. Please note
│ that the matching is done using a case-sensitive comparison. Check your
│ federated identity credential Subject, Audience and Issuer against the
│ presented assertion.
│ https://learn.microsoft.com/entra/workload-id/workload-identity-federation
│ Trace ID: 00000000-0000-0000-0000-000000000000 Correlation ID:
│ 00000000-0000-0000-0000-000000000000 Timestamp: 2024-10-01 07:45:48Z
╵

##[error]Script failed with exit code: 1
```

### 🔬 How to reproduce?

setup a datasource

```
data "fabric_capacity" "capacity" {
  display_name = var.capacity_name
}
```
and run it in a Azure Devops Pipeline. 

### 🏗️ Code Sample / Log

```yml
    - task: AzureCLI@2
      displayName: 'Trigger Deployment'
      env:
        TF_IN_AUTOMATION: true
        ARM_USE_OIDC: true
        FABRIC_TENANT_ID: 00000000-0000-0000-0000-000000000000
        FABRIC_CLIENT_ID: <ID of the SPN inside of the ADO service connection>
        FABRIC_OIDC_REQUEST_TOKEN: $(System.AccessToken)
        FABRIC_AZURE_DEVOPS_SERVICE_CONNECTION_ID: <name of the SC>
      inputs:
        azureSubscription: <name of the SC>
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -eux
          terraform -version
          terraform init
          terraform plan -out=fabric_plan.tfplan -var-file=$(Build.SourcesDirectory)/config/lab/terraform.tfvars
          terraform apply -auto-approve fabric_plan.tfplan
        workingDirectory: $(Build.SourcesDirectory)/infra
```

### 📈 Expected behavior

Followed the documentation and guidelines so far. What am I missing?

### 🌌 Environment (Provider Version)

v0.1.0-beta.3

### 🌌 Environment (Terraform Version)

v1.9.6

### 🌌 Environment (OS)

Linux

### 🔰 Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by micahel71** [comment]
Update: Switching to a Service Connection with a Client Secret Setup (SPN), I get this:
```
Terraform has been successfully initialized!
+ terraform plan -out=fabric_plan.tfplan -var-file=/home/vsts/work/1/self/config/lab/terraform.tfvars
data.fabric_capacity.capacity: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: list operation
│ 
│   with data.fabric_capacity.capacity,
│   on workspace.tf line 1, in data "fabric_capacity" "capacity":
│    1: data "fabric_capacity" "capacity" {
│ 
│ Could not list resource: The feature is not available
╵

##[error]Script failed with exit code: 1
```
Ist this true?
According to this https://registry.terraform.io/providers/microsoft/fabric/latest/docs/data-sources/capacity SPN should work?!?

**Comment by DariuszPorowski** [comment]
Hi @micahel71

`task: AzureCLI@2` is technically Az CLI that uses own native cli authentication. So, you do not have to specify any additional configuration for OIDC as long as `inputs.azureSubscription` points to Workload Identity connection.

```yaml
- task: AzureCLI@2
  displayName: 'Trigger Deployment'
  env:
    TF_IN_AUTOMATION: true
    FABRIC_USE_CLI: true
  inputs:
    azureSubscription: <name of the SC>
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -eux
      terraform -version
      terraform init
      terraform plan -out=fabric_plan.tfplan -var-file=$(Build.SourcesDirectory)/config/lab/terraform.tfvars
      terraform apply -auto-approve fabric_plan.tfplan
    workingDirectory: $(Build.SourcesDirectory)/infra
```

Additional configuration for OIDC is only required when you want to use provider-level authentication without using Az CLI. Example snippet:

```yaml
- script: |
    set -eux
    terraform -version
    terraform init
    terraform plan -out=fabric_plan.tfplan -var-file=$(Build.SourcesDirectory)/config/lab/terraform.tfvars
    terraform apply -auto-approve fabric_plan.tfplan
  env:
    TF_IN_AUTOMATION: true
    FABRIC_USE_OIDC: true
    FABRIC_TENANT_ID: 00000000-0000-0000-0000-000000000000
    FABRIC_CLIENT_ID: 00000000-0000-0000-0000-000000000000
    FABRIC_OIDC_REQUEST_TOKEN: $(System.AccessToken)
    FABRIC_AZURE_DEVOPS_SERVICE_CONNECTION_ID: 00000000-0000-0000-0000-000000000000
  workingDirectory: $(Build.SourcesDirectory)/infra
```

Please note that `FABRIC_AZURE_DEVOPS_SERVICE_CONNECTION_ID` is not a Service Connection name, but ID (GUID). You can find it in the Service Connection URL after you go to the SC details.
`https://dev.azure.com/<ORG>/<PROJECT>/_settings/adminservices?resourceId=<YOUR SC ID>`
