### ISSUE TITLE
[BUG] Authentication using user assigned identity in GitHub action

### ISSUE THREAD

**Issue by dsfrederic-cgk** [microsoft/terraform-provider-fabric#230]
### 🐛 What happened?

List operation on capacity does not seem to work. 

### 🏗️ Code Sample / Log

This github action code 

```yaml
name: Terraform Deploy

on:
  workflow_call:
    inputs:
        scope:
          required: true
          type: string
        workspace:
          required: false
          type: string
          default: 'default'
          description: 'Terraform workspace to use'
        path:
          required: true
          type: string
          description: 'Relative path of the Terraform code'
        arguments:
          required: false
          type: string
          default: ''
          description: 'Additional arguments to pass to Terraform commands'
        init_arguments:
          required: false
          type: string
          default: ''
          description: 'Additional arguments to pass to Terraform init command'
    
permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.scope }}-plan
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
      ARM_USE_MSI: false
      TF_IN_AUTOMATION: true
      FABRIC_USE_MSI: false
      FABRIC_USE_OIDC: true
      FABRIC_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      FABRIC_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform init
        shell: bash
        run: |
          cd ${{ inputs.path }}
          terraform init ${{ inputs.arguments }} ${{ inputs.init_arguments }}

      - name: Run Terraform Workspace Select
        shell: bash
        run: |
          cd ${{ inputs.path }}
          terraform workspace select ${{ inputs.workspace }} || terraform workspace new ${{ inputs.workspace }}

      - name: Run Terraform Plan
        id: plan
        shell: bash
        run: |
          cd ${{ inputs.path }}  
          terraform plan -out terraform.plan ${{ inputs.arguments }}

      - name: Publish Terraform Plan Artefact
        uses: actions/upload-artifact@v4
        with:
          name: plan_${{ inputs.workspace }}
          path: ${{ inputs.path }}
          include-hidden-files: true # To include .terraform directory


  terraform-apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.workspace == 'default' && inputs.scope || format('{0}-{1}' ,inputs.scope, inputs.workspace)}}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
      ARM_USE_MSI: false
      TF_IN_AUTOMATION: true
      FABRIC_USE_MSI: false
      FABRIC_USE_OIDC: true
      FABRIC_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      FABRIC_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    needs: terraform-plan
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: plan_${{ inputs.workspace }}

      - name: Log into Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Terraform Apply
        shell: bash
        run: |
          chmod -R a+x .terraform/*
          terraform workspace select ${{ inputs.workspace }}
          terraform apply terraform.plan
```

This identity is added as capacity administrator. I've also tried to give the entra role Fabric administrator without any luck

### 📷 Screenshots

![Image](https://github.com/user-attachments/assets/3e15512f-def5-4e29-838f-7b08d48c14c3)

### 📈 Expected behavior

No authentication issues

### 🌌 Environment (Provider Version)

v0.1.0-beta.7

### 🌌 Environment (Terraform Version)

1.10.5

### 🌌 Environment (OS)

Linux

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
