### ISSUE TITLE
[BUG] data source "fabric_capacity" returning error when using service principal

### ISSUE THREAD

**Issue by kirillzekn** [microsoft/terraform-provider-fabric#455]
### 🐛 What happened?

When running terraform plan, the terraform-provider-fabric v1.1.0 plugin crashes with a segmentation fault (SIGSEGV) during the dataSourceCapacity.Read call. The error appears to be due to a nil pointer dereference within the provider code.

### 🔬 How to reproduce?

Steps to Reproduce

1. Use the terraform-provider-fabric v1.1.0 provider.
2. Reference a data "fabric_capacity" block (with valid or invalid config, see code below).
3. Run terraform plan.

```
Example Terraform Configuration
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0.0"
    }
    fabric = {
      source  = "microsoft/fabric"
      version = ">= 1.1.0"
    }
  }
}

resource "azurerm_fabric_capacity" "this" {
  name                = var.fabric_capacity_name
  location            = var.location
  resource_group_name = var.resource_group_name
  administration_members = var.fabric_capacity_admin_upns
  sku {
    name = var.fabric_capacity_sku
    tier = "Fabric"
  }
  tags = var.tags
}

data "fabric_capacity" "this" {
  display_name = azurerm_fabric_capacity.this.name
  lifecycle {
    postcondition {
      condition     = self.state == "Active"
      error_message = "Fabric Capacity is not in Active state. Please check the Fabric Capacity status."
    }
  }
}
```

Additional Information

1. Terraform version: 1.12.0
2. Fabric provider version: 1.1.0
3. OS: ( Ubuntu 22.04 in Azure Pipeline)
4. Backend: (e.g. azurerm)
5. For service principal I'm using the same SPN which was created automatically during establishing Azure Service Connection (Workload identity federation (automatic)).
6. Service principal can use Fabric APIs is ENABLED for THE ENTIRE ORGANIZATION.
7. Service Principal has contributor role on Azure Resource Group level. 

### 🏗️ Code Sample / Log

```
The plugin6.(*GRPCProvider).ReadDataSource request was cancelled.

Stack trace from the terraform-provider-fabric_v1.1.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xdb244d]

goroutine 11 [running]:
github.com/microsoft/terraform-provider-fabric/internal/services/capacity.(*dataSourceCapacity).Read(0xc000478700, {0x1537048, 0xc00047da10}, {{{{0x1545890, 0xc000503bf0}, {0x11b9920, 0xc000503b00}}, {0x1549198, 0xc00017b840}}, {{{0x0, ...}, ...}, ...}, ...}, ...)
	github.com/microsoft/terraform-provider-fabric/internal/services/capacity/data_capacity.go:93 +0x26d
...
Error: The terraform-provider-fabric_v1.1.0 plugin crashed!
```

### 📈 Expected behavior

data source should capture fabric_capacity ID

### 🌌 Environment (Provider Version)

1.1.0

### 🌌 Environment (Terraform Version)

1.12.0

### 🌌 Environment (OS)

Linux

### 🔰 Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by badeamarjieh** [comment]
Hi @kirillzekn.
Thanks for reporting this—we'll investigate to pinpoint the bug and update you once we have a fix.

**Comment by kirillzekn** [comment]
Would like to provide updates, 

1. My Azure-pipeline.yaml code is following:
```
trigger: none 
parameters:
  - name: environment
    displayName: "Environment"
    type: string

stages:
- stage: TerraformPipeline
  displayName: "Terraform Pipeline"
  jobs:
  - job: TerraformJob
    displayName: "Execute Terraform Tasks"
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      terraformWorkingDirectory: "terraform" 
      FABRIC_CLIENT_ID: $(LIB_CLIENT_ID)
      FABRIC_TENANT_ID: $(LIB_TENANT_ID)
      FABRIC_OIDC_REQUEST_TOKEN: $(System.AccessToken) 
      FABRIC_AZURE_DEVOPS_SERVICE_CONNECTION_ID: $(LIB_AZURE_DEVOPS_SERVICE_CONNECTION_ID)
      FABRIC_USE_OIDC: "true"
    steps:


    - checkout: self
      displayName: "Checkout Terraform Code"

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Initialize Terraform Backend"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDirectory)'
        backendServiceArm: ...
        backendAzureRmResourceGroupName: ...
        backendAzureRmStorageAccountName: ...
        backendAzureRmContainerName: ...
        backendAzureRmKey: ...
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Generate Terraform Plan"
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: ...
        workingDirectory: $(terraformWorkingDirectory)
        terraformVersion: 'latest'
```

2. In debug I found following errors:

`2025-05-21T12:29:45.734Z [ERROR] provider.terraform-provider-fabric_v1.1.0: Failed to initialize authentication: client_secret="***" oidc_token="***" tf_provider_addr=registry.terraform.io/microsoft/fabric tf_req_id=69......23 use_oidc=true use_dev_cli=false azure_devops_service_connection_id="$(LIB_AZURE_DEVOPS_SERVICE_CONNECTION_ID)" client_certificate="***" client_certificate_password="***" @caller=github.com/microsoft/terraform-provider-fabric/internal/provider/provider.go:125 client_id="$(LIB_CLIENT_ID)" oidc_token_file_path="" client_certificate_file_path="" client_id_file_path="" endpoint=map[] preview=false client_secret_file_path="" error="invalid tenantID. You can locate your tenantID by following the instructions listed here: https://learn.microsoft.com/partner-center/find-ids-and-domain-names" use_msi=false auxiliary_tenant_ids=[] environment=public oidc_request_token="***" tenant_id="$(LIB_TENANT_ID)" tf_rpc=ConfigureProvider timeout=map[] use_cli=false @module=fabric oidc_request_url="***" timestamp=2025-05-21T12:29:45.734Z`

3. I'm storing Service Connection details including TENANT ID in Azure Pipelines variables (LIB section of Pipeline)
FABRIC_CLIENT_ID: $(LIB_CLIENT_ID)
FABRIC_TENANT_ID: $(LIB_TENANT_ID)
FABRIC_OIDC_REQUEST_TOKEN: $(System.AccessToken) 
FABRIC_AZURE_DEVOPS_SERVICE_CONNECTION_ID: $(LIB_AZURE_DEVOPS_SERVICE_CONNECTION_ID)

**Workaround:**
And looks like these variables could not be resolved properly into actual values. Once I porvided in my azure-pipeline file values for these variables explicitly, issue was resolved.
```
      FABRIC_CLIENT_ID: "3.....d"
      FABRIC_TENANT_ID: "f.....d" 
      FABRIC_OIDC_REQUEST_TOKEN: $(System.AccessToken) 
      FABRIC_AZURE_DEVOPS_SERVICE_CONNECTION_ID: "4.....2"
```

Would be glad if you could advise how to store FABRIC_XXX variables securely and refer to them ?
